import 'package:deadzon/features/statusbar/statusbar_models.dart';
import 'package:flutter/material.dart';

class StatusBarHelper {
  const StatusBarHelper._();

  static final List<StatusBarSectionDefinition> sections = <StatusBarSectionDefinition>[
    const StatusBarSectionDefinition(
      id: 'resize_statusbar',
      title: 'Resize statusbar',
      subtitle: 'Fine tune margins, cutout behavior, and safe spacing',
      icon: Icons.crop_rounded,
      accentColor: Color(0xFF74E4D0),
      displayOrder: 1,
      previewLabel: 'Geometry',
      routeSlug: 'resize',
      sourceXmlReference: 'reference/mezo/xml/settings_resize_elite.xml',
      legacyPreferenceGroup: 'settings_resize_elite',
    ),
    const StatusBarSectionDefinition(
      id: 'battery',
      title: 'Battery',
      subtitle: 'Battery icon style, size, percent, and charging visuals',
      icon: Icons.battery_6_bar_rounded,
      accentColor: Color(0xFF8BF3AE),
      displayOrder: 2,
      previewLabel: 'Battery',
      routeSlug: 'battery',
      sourceXmlReference: 'reference/mezo/xml/my_battery_settings.xml',
      legacyPreferenceGroup: 'my_battery_settings',
    ),
    const StatusBarSectionDefinition(
      id: 'clock',
      title: 'Clock',
      subtitle: 'Adjust clock style, format, animation, and precision',
      icon: Icons.access_time_rounded,
      accentColor: Color(0xFF8DD0FF),
      displayOrder: 3,
      previewLabel: 'Time',
      routeSlug: 'clock',
      sourceXmlReference: 'reference/mezo/xml/my_clock_settings.xml',
      legacyPreferenceGroup: 'my_clock_settings',
    ),
    const StatusBarSectionDefinition(
      id: 'netspeed',
      title: 'Netspeed',
      subtitle: 'Show live traffic indicator with refined text behavior',
      icon: Icons.speed_rounded,
      accentColor: Color(0xFF9EE3FF),
      displayOrder: 4,
      previewLabel: 'Speed',
      routeSlug: 'netspeed',
      sourceXmlReference: 'reference/mezo/xml/speed_elite.xml',
      legacyPreferenceGroup: 'speed_elite',
    ),
    const StatusBarSectionDefinition(
      id: 'network',
      title: 'Network',
      subtitle: 'Control cellular and Wi-Fi indicators across layouts',
      icon: Icons.signal_cellular_alt_rounded,
      accentColor: Color(0xFF9AB2FF),
      displayOrder: 5,
      previewLabel: 'Signal',
      routeSlug: 'network',
      sourceXmlReference: 'reference/mezo/xml/elem_net_elite.xml',
      legacyPreferenceGroup: 'elem_net_elite',
    ),
    const StatusBarSectionDefinition(
      id: 'notification_icons',
      title: 'Notification icons',
      subtitle: 'Visibility and spacing for compact notification symbols',
      icon: Icons.notifications_rounded,
      accentColor: Color(0xFFFFBE87),
      displayOrder: 6,
      previewLabel: 'Notifications',
      routeSlug: 'notification-icons',
      sourceXmlReference: 'reference/mezo/xml/settings_notif.xml',
      legacyPreferenceGroup: 'settings_notif',
    ),
    const StatusBarSectionDefinition(
      id: 'status_icons',
      title: 'Status icons',
      subtitle: 'Choose which utility icons stay visible and where',
      icon: Icons.widgets_rounded,
      accentColor: Color(0xFFA9F4E0),
      displayOrder: 7,
      previewLabel: 'Utility',
      routeSlug: 'status-icons',
      sourceXmlReference: 'reference/mezo/xml/settings_status_icons.xml',
      legacyPreferenceGroup: 'settings_status_icons',
    ),
    const StatusBarSectionDefinition(
      id: 'date',
      title: 'Date',
      subtitle: 'Date format, size, spacing, and accent styling',
      icon: Icons.calendar_month_rounded,
      accentColor: Color(0xFFB7C6FF),
      displayOrder: 8,
      previewLabel: 'Date',
      routeSlug: 'date',
      sourceXmlReference: 'reference/mezo/xml/settings_date_elite.xml',
      legacyPreferenceGroup: 'settings_date_elite',
    ),
    const StatusBarSectionDefinition(
      id: 'weather',
      title: 'Weather',
      subtitle: 'Configure weather text, icon style, and placement',
      icon: Icons.cloud_rounded,
      accentColor: Color(0xFF8DE8FF),
      displayOrder: 9,
      previewLabel: 'Weather',
      routeSlug: 'weather',
      sourceXmlReference: 'reference/mezo/xml/settings_weather_icon.xml',
      legacyPreferenceGroup: 'settings_weather_icon',
    ),
    const StatusBarSectionDefinition(
      id: 'prompt_icon',
      title: 'Prompt icon',
      subtitle: 'Tune prompt icon size, color, and reveal behavior',
      icon: Icons.chat_bubble_outline_rounded,
      accentColor: Color(0xFFE2B4FF),
      displayOrder: 10,
      previewLabel: 'Prompt',
      routeSlug: 'prompt-icon',
      sourceXmlReference: 'reference/mezo/xml/statusbar_elem_prompt.xml',
      legacyPreferenceGroup: 'statusbar_elem_prompt',
    ),
    const StatusBarSectionDefinition(
      id: 'background',
      title: 'Background',
      subtitle: 'Blend background overlays, blur, and shadow depth',
      icon: Icons.format_paint_rounded,
      accentColor: Color(0xFF94E0D4),
      displayOrder: 11,
      previewLabel: 'Backdrop',
      routeSlug: 'background',
      sourceXmlReference: 'reference/mezo/xml/settings_iback_elite.xml',
      legacyPreferenceGroup: 'settings_iback_elite',
    ),
  ];

  static List<StatusBarSectionDefinition> orderedSections() {
    final ordered = List<StatusBarSectionDefinition>.from(sections);
    ordered.sort((a, b) => a.displayOrder.compareTo(b.displayOrder));
    return ordered;
  }
}
