import 'package:deadzon/features/statusbar/statusbar_models.dart';
class StatusbarSourceInventory {
  const StatusbarSourceInventory._();

  static final Map<String, List<StatusBarSettingItem>> extractedBySection = <String, List<StatusBarSettingItem>>{
    'resize_statusbar': <StatusBarSettingItem>[
      StatusBarSettingItem(
        legacyKey: 'status_bar_elem_center_in_island',
        title: 'Status Bar Center In Island',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: true,
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_resize_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'custom_status_bar_top',
        title: 'Custom Status Bar Top',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 2.0,
        min: 0.0,
        max: 40.0,
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_resize_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'custom_status_bar_left_right',
        title: 'Custom Status Bar Left Right',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 0.0,
        min: 0.0,
        max: 200.0,
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_resize_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_bar_element_cutout_padding',
        title: 'Status Bar Element Cutout Padding',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 35.0,
        min: 0.0,
        max: 150.0,
        intentAction: 'my.settings.intent.element_position_cutout.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_resize_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_bar_element_cutout_type',
        title: 'Status Bar Element Cutout Type',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '1',
        intentAction: 'my.settings.intent.element_position_cutout.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '1'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_resize_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_bar_element_cutout_center',
        title: 'Status Bar Element Cutout Center',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '2',
        intentAction: 'my.settings.intent.element_position_cutout.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '2'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_resize_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_bar_element_cutout_camera_width',
        title: 'Status Bar Element Cutout Camera Width',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 80.0,
        min: 1.0,
        max: 200.0,
        intentAction: 'my.settings.intent.element_position_cutout.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_resize_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_bar_element_cutout_left',
        title: 'Status Bar Element Cutout Left',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '2',
        intentAction: 'my.settings.intent.element_position_cutout.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '2'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_resize_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_bar_element_cutout_padding_left_camera',
        title: 'Status Bar Element Cutout Padding Left Camera',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 75.0,
        min: 10.0,
        max: 150.0,
        intentAction: 'my.settings.intent.element_position_cutout.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_resize_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_bar_element_cutout_left_not_calculate',
        title: 'Status Bar Element Cutout Left Not Calculate',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '2',
        intentAction: 'my.settings.intent.element_position_cutout.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '2'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_resize_elite.smali',
      ),
    ],
    'battery': <StatusBarSettingItem>[
      StatusBarSettingItem(
        legacyKey: 'elem_bat_element_visible',
        title: 'Bat Element Visible',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: true,
        intentAction: 'my.settings.intent.element_visibility_change.CHANGE',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_indicator_style',
        title: 'Battery Indicator Style',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '1',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '1'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'use_legacy_drawable',
        title: 'Use Legacy Drawable',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '0',
        intentAction: 'my.settings.intent.use_legacy_drawable.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'android.theme.customization.battery_icon',
        title: 'Android.Theme.Customization.Battery Icon',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '0',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'com.android.settingslib.miuisettings.preference.Preference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'batteryview_zoom',
        title: 'Batteryview Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 150.0,
        intentAction: 'my.settings.intent.batteryview_zoom.CHANGE',
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'batteryview_scale',
        title: 'Batteryview Scale',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 200.0,
        intentAction: 'my.settings.intent.batteryview_zoom.CHANGE',
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'batteryview_division',
        title: 'Batteryview Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 0.0,
        min: -50.0,
        max: 50.0,
        intentAction: 'my.settings.intent.batteryview_zoom.CHANGE',
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_zoom',
        title: 'Battery Percent Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 14.0,
        min: 1.0,
        max: 30.0,
        intentAction: 'my.settings.intent.battery_percent_zoom.CHANGE',
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_division',
        title: 'Battery Percent Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 20.0,
        min: 0.0,
        max: 30.0,
        intentAction: 'my.settings.intent.battery_percent_zoom.CHANGE',
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_charge_zoom',
        title: 'Battery Charge Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 150.0,
        intentAction: 'my.settings.intent.battery_charge_color.CHANGE',
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_charge_scale',
        title: 'Battery Charge Scale',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 150.0,
        intentAction: 'my.settings.intent.battery_charge_color.CHANGE',
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_charge_division',
        title: 'Battery Charge Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 0.0,
        min: -50.0,
        max: 50.0,
        intentAction: 'my.settings.intent.battery_charge_color.CHANGE',
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_digit_zoom',
        title: 'Battery Percent Digit Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 24.0,
        min: 1.0,
        max: 50.0,
        intentAction: 'my.settings.intent.battery_percent_digit_color.CHANGE',
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_digit_division',
        title: 'Battery Percent Digit Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 20.0,
        min: 0.0,
        max: 30.0,
        intentAction: 'my.settings.intent.battery_percent_digit_color.CHANGE',
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'text_bat_color_0',
        title: 'Text Bat Color 0',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.text_bat_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'text_bat_color_1',
        title: 'Text Bat Color 1',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.text_bat_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'text_bat_color_2',
        title: 'Text Bat Color 2',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.text_bat_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'text_bat_color_3',
        title: 'Text Bat Color 3',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.text_bat_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'text_bat_color_4',
        title: 'Text Bat Color 4',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.text_bat_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_digit_color',
        title: 'Battery Percent Digit Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.battery_percent_digit_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_charge_color',
        title: 'Battery Charge Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.battery_charge_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_typefase',
        title: 'Battery Percent Typefase',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: 'Default',
        intentAction: 'my.settings.intent.battery_percent_zoom.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: 'Default'),
        ],
        preferenceType: 'MiuiFontStylePreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_typefasestyle',
        title: 'Battery Percent Typeface Style',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '1',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Normal', value: '0'),
          StatusBarOption(label: 'Bold', value: '1'),
          StatusBarOption(label: 'Italic', value: '2'),
          StatusBarOption(label: 'Bold italic', value: '3'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_mark_enable',
        title: 'Battery Percent Mark Enable',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: true,
        intentAction: 'my.settings.intent.battery_percent_mark_enable.CHANGE',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_mark_settings_enable',
        title: 'Battery Percent Mark Settings Enable',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: false,
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_mark_typefase',
        title: 'Battery Percent Mark Typefase',
        subtitle: 'Depends on battery_percent_mark_settings_enable • Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: 'Default',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: 'Default'),
        ],
        preferenceType: 'MiuiFontStylePreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_mark_typefasestyle',
        title: 'Battery Percent Mark Typeface Style',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '1',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Normal', value: '0'),
          StatusBarOption(label: 'Bold', value: '1'),
          StatusBarOption(label: 'Italic', value: '2'),
          StatusBarOption(label: 'Bold italic', value: '3'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'text_bat_color_mark_0',
        title: 'Text Bat Color Mark 0',
        subtitle: 'Depends on battery_percent_mark_settings_enable • Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'text_bat_color_mark_1',
        title: 'Text Bat Color Mark 1',
        subtitle: 'Depends on battery_percent_mark_settings_enable • Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'text_bat_color_mark_2',
        title: 'Text Bat Color Mark 2',
        subtitle: 'Depends on battery_percent_mark_settings_enable • Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'text_bat_color_mark_3',
        title: 'Text Bat Color Mark 3',
        subtitle: 'Depends on battery_percent_mark_settings_enable • Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'text_bat_color_mark_4',
        title: 'Text Bat Color Mark 4',
        subtitle: 'Depends on battery_percent_mark_settings_enable • Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: 0x00000000,
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_mark_zoom',
        title: 'Battery Percent Mark Zoom',
        subtitle: 'Depends on battery_percent_mark_settings_enable • Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 14.0,
        min: 1.0,
        max: 30.0,
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'battery_percent_mark_division',
        title: 'Battery Percent Mark Division',
        subtitle: 'Depends on battery_percent_mark_settings_enable • Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 20.0,
        min: 10.0,
        max: 30.0,
        preferenceType: 'XMiuiSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_battery_settings.smali',
      ),
    ],
    'clock': <StatusBarSettingItem>[
      StatusBarSettingItem(
        legacyKey: 'elem_clock_element_visible',
        title: 'Clock Element Visible',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: true,
        intentAction: 'my.settings.intent.element_visibility_change.CHANGE',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_clock_zoom',
        title: 'Status Clock Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 14.0,
        min: 0.0,
        max: 30.0,
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_clock_division',
        title: 'Status Clock Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 20.0,
        min: 0.0,
        max: 30.0,
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_clock_color',
        title: 'Status Clock Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: '#00000000',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_clock_typefase',
        title: 'Status Clock Typefase',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: 'default',
        intentAction: 'my.settings.intent.CLOCK_TYPEFACE_CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'MiuiFontStylePreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_clock_anim_style',
        title: 'Status Clock Anim Style',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '1',
        intentAction: 'my.intent.action.REFRESH_STATUSBAR',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '1'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_clock_dots_enable',
        title: 'Status Clock Dots Enable',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: true,
        intentAction: 'my.intent.action.REFRESH_STATUSBAR',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_clock_second_enable',
        title: 'Status Clock Second Enable',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: true,
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'clock_mezo_time_style',
        title: 'Clock Mezo Time Style',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: false,
        intentAction: 'my.intent.action.REFRESH_STATUSBAR',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'expanded_clock_zoom',
        title: 'Expanded Clock Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 50.0,
        min: 1.0,
        max: 100.0,
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'expanded_clock_division',
        title: 'Expanded Clock Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 15.0,
        min: 10.0,
        max: 30.0,
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'expanded_clock_color',
        title: 'Expanded Clock Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: '#00000000',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'expanded_clock_dots_enable',
        title: 'Expanded Clock Dots Enable',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: false,
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'expanded_clock_anim_style',
        title: 'Expanded Clock Anim Style',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '0',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'expanded_clock_second_enable',
        title: 'Expanded Clock Second Enable',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: false,
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'Notif_date_zoom',
        title: 'Notif Date Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 18.0,
        min: 1.0,
        max: 70.0,
        intentAction: 'my.settings.intent.Notif_date_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'Notif_date_division',
        title: 'Notif Date Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 15.0,
        min: 10.0,
        max: 50.0,
        intentAction: 'my.settings.intent.Notif_date_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'Notif_date_color',
        title: 'Notif Date Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: '#00000000',
        intentAction: 'my.settings.intent.Notif_date_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'Notif_date_typefase',
        title: 'Notif Date Typefase',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: 'default',
        intentAction: 'my.settings.intent.Notif_date_color.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'MiuiFontStylePreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'Notif_date_format',
        title: 'Notif Date Format',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '0',
        intentAction: 'my.settings.intent.DATE_FORMAT_CHANGED',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'weather_notif_text_zoom',
        title: 'Weather Notif Text Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 16.0,
        min: 5.0,
        max: 20.0,
        intentAction: 'my.settings.intent.weather_notif_text_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'weather_notif_text_color',
        title: 'Weather Notif Text Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: '#00000000',
        intentAction: 'my.settings.intent.weather_notif_text_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'weather_notif_text_typefase',
        title: 'Weather Notif Text Typefase',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: 'default',
        intentAction: 'my.settings.intent.weather_notif_text_color.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'MiuiFontStylePreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'Settingsfachen_color',
        title: 'Settingsfachen Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: '#00000000',
        intentAction: 'my.settings.intent.Settingsfachen_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'Settingsfachen_zoom',
        title: 'Settingsfachen Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 130.0,
        min: 50.0,
        max: 200.0,
        intentAction: 'my.settings.intent.Settingsfachen_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'Settingsfachen_scale',
        title: 'Settingsfachen Scale',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 200.0,
        intentAction: 'my.settings.intent.Settingsfachen_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'Settingsfachen_division',
        title: 'Settingsfachen Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 0.0,
        min: -50.0,
        max: 50.0,
        intentAction: 'my.settings.intent.Settingsfachen_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/my_clock_settings.smali',
      ),
    ],
    'netspeed': <StatusBarSettingItem>[
      StatusBarSettingItem(
        legacyKey: 'status_bar_show_network_speed',
        title: 'Status Bar Show Network Speed',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '1',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '1'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'net_speed_zoom',
        title: 'Net Speed Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 12.0,
        min: 1.0,
        max: 70.0,
        intentAction: 'my.settings.intent.net_speed_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'net_speed_division',
        title: 'Net Speed Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 20.0,
        min: 0.0,
        max: 30.0,
        intentAction: 'my.settings.intent.net_speed_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'net_speed_height',
        title: 'Net Speed Height',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 50.0,
        min: 30.0,
        max: 150.0,
        intentAction: 'my.settings.intent.net_speed_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'net_speed_color',
        title: 'Net Speed Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: '#00000000',
        intentAction: 'my.settings.intent.net_speed_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_bar_network_speed_interval',
        title: 'Status Bar Network Speed Interval',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 1000.0,
        min: 500.0,
        max: 4000.0,
        step: 500.0,
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'net_speed_typefase',
        title: 'Net Speed Typefase',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: 'default',
        intentAction: 'my.settings.intent.net_speed_color.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'MiuiFontStylePreference',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
    ],
    'network': <StatusBarSettingItem>[
      StatusBarSettingItem(
        legacyKey: 'simview_zoom',
        title: 'Simview Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 200.0,
        intentAction: 'my.settings.intent.sim_zoom.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'simview_scale',
        title: 'Simview Scale',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 200.0,
        intentAction: 'my.settings.intent.sim_zoom.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'simview_division',
        title: 'Simview Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 0.0,
        min: -50.0,
        max: 50.0,
        intentAction: 'my.settings.intent.sim_zoom.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'mobile_type_zoom',
        title: 'Mobile Type Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 20.0,
        min: 1.0,
        max: 70.0,
        intentAction: 'my.settings.intent.mobile_type_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'mobile_type_division',
        title: 'Mobile Type Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 10.0,
        min: -30.0,
        max: 30.0,
        intentAction: 'my.settings.intent.mobile_type_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'mobile_inout_zoom',
        title: 'Mobile Inout Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 200.0,
        intentAction: 'my.settings.intent.mobile_inout_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'mobile_inout_scale',
        title: 'Mobile Inout Scale',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 200.0,
        intentAction: 'my.settings.intent.mobile_inout_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'mobile_inout_division',
        title: 'Mobile Inout Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 0.0,
        min: -50.0,
        max: 50.0,
        intentAction: 'my.settings.intent.mobile_inout_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
    ],
    'notification_icons': <StatusBarSettingItem>[
      StatusBarSettingItem(
        legacyKey: 'reverse_notification_sorting_order',
        title: 'Reverse Notification Sorting Order',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: false,
        intentAction: 'my.settings.intent.notif_icon_color.CHANGE',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_notif.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'notif_icon_color',
        title: 'Notif Icon Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: '#00000000',
        intentAction: 'my.settings.intent.notif_icon_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_notif.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'notif_icon_zoom',
        title: 'Notif Icon Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 10.0,
        max: 150.0,
        intentAction: 'my.settings.intent.notif_icon_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_notif.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'notif_icon_scale',
        title: 'Notif Icon Scale',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 0.0,
        max: 150.0,
        intentAction: 'my.settings.intent.notif_icon_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_notif.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'notif_icon_division',
        title: 'Notif Icon Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 0.0,
        min: -50.0,
        max: 50.0,
        intentAction: 'my.settings.intent.notif_icon_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_notif.smali',
      ),
    ],
    'status_icons': <StatusBarSettingItem>[
      StatusBarSettingItem(
        legacyKey: 'elem_status_element_visible',
        title: 'Status Element Visible',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: true,
        intentAction: 'my.settings.intent.element_visibility_change.CHANGE',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_status_icons.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_icon_color',
        title: 'Status Icon Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: '#00000000',
        intentAction: 'my.settings.intent.status_icon_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_status_icons.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_icon_zoom',
        title: 'Status Icon Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 200.0,
        intentAction: 'my.settings.intent.status_icon_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_status_icons.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_icon_scale',
        title: 'Status Icon Scale',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 100.0,
        min: 50.0,
        max: 150.0,
        intentAction: 'my.settings.intent.status_icon_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_status_icons.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_icon_division',
        title: 'Status Icon Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 0.0,
        min: -50.0,
        max: 50.0,
        intentAction: 'my.settings.intent.status_icon_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_status_icons.smali',
      ),
    ],
    'date': <StatusBarSettingItem>[
      StatusBarSettingItem(
        legacyKey: 'elem_date_element_visible',
        title: 'Date Element Visible',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: false,
        intentAction: 'my.settings.intent.element_visibility_change.CHANGE',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_date_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_date_color',
        title: 'Status Date Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: '#00000000',
        intentAction: 'my.settings.intent.status_date_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_date_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_date_zoom',
        title: 'Status Date Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 10.0,
        min: 1.0,
        max: 30.0,
        intentAction: 'my.settings.intent.status_date_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_date_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_date_division',
        title: 'Status Date Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 20.0,
        min: 0.0,
        max: 30.0,
        intentAction: 'my.settings.intent.status_date_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_date_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_date_typefase',
        title: 'Status Date Typefase',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: 'default',
        intentAction: 'my.settings.intent.status_date_color.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'MiuiFontStylePreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_date_elite.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'statusbar_date_format',
        title: 'Statusbar Date Format',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: '0',
        intentAction: 'my.settings.intent.DATE_FORMAT_CHANGED',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'XMiuiDropDownPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_date_elite.smali',
      ),
    ],
    'weather': <StatusBarSettingItem>[
      StatusBarSettingItem(
        legacyKey: 'elem_weather_element_visible',
        title: 'Weather Element Visible',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: true,
        intentAction: 'my.settings.intent.element_visibility_change.CHANGE',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_weather_icon.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'weather_anim_enable',
        title: 'Weather Anim Enable',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.toggle,
        group: 'Advanced (source-preserved)',
        defaultValue: false,
        intentAction: 'my.settings.intent.weather_anim_enable.CHANGE',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_weather_icon.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_weather_color',
        title: 'Status Weather Color',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.color,
        group: 'Advanced (source-preserved)',
        defaultValue: '#00000000',
        intentAction: 'my.settings.intent.status_weather_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_weather_icon.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_weather_zoom',
        title: 'Status Weather Zoom',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 16.0,
        min: 1.0,
        max: 30.0,
        intentAction: 'my.settings.intent.status_weather_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_weather_icon.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_weather_division',
        title: 'Status Weather Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 20.0,
        min: 0.0,
        max: 30.0,
        intentAction: 'my.settings.intent.status_weather_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_weather_icon.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'status_weather_typefase',
        title: 'Status Weather Typefase',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.select,
        group: 'Advanced (source-preserved)',
        defaultValue: 'default',
        intentAction: 'my.settings.intent.status_weather_color.CHANGE',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Default', value: '0'),
        ],
        preferenceType: 'MiuiFontStylePreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_weather_icon.smali',
      ),
    ],
    'prompt_icon': <StatusBarSettingItem>[
      StatusBarSettingItem(
        legacyKey: 'elem_prompt_scale',
        title: 'Prompt Scale',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 75.0,
        min: 50.0,
        max: 150.0,
        intentAction: 'my.settings.intent.elem_prompt_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_elem_prompt.smali',
      ),
      StatusBarSettingItem(
        legacyKey: 'elem_prompt_division',
        title: 'Prompt Division',
        subtitle: 'Source-preserved setting from old mod',
        controlType: StatusBarControlType.slider,
        group: 'Advanced (source-preserved)',
        defaultValue: 0.0,
        min: -50.0,
        max: 50.0,
        intentAction: 'my.settings.intent.elem_prompt_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_elem_prompt.smali',
      ),
    ],
  };
}
