import 'package:deadzon/features/statusbar/data/mezo_resize_source.dart';
import 'package:deadzon/features/statusbar/statusbar_models.dart';
import 'package:deadzon/features/statusbar/statusbar_source_inventory.dart';
import 'package:deadzon/features/statusbar/statusbar_strings.dart';

class StatusBarMapper {
  const StatusBarMapper._();

  static List<StatusBarSettingItem> settingsForSection(String sectionId) {
    final curated = _mapped[sectionId] ?? const <StatusBarSettingItem>[];
    final extracted = StatusbarSourceInventory.extractedBySection[sectionId] ?? const <StatusBarSettingItem>[];
    if (extracted.isEmpty) {
      return curated;
    }
    return _mergeByLegacyKeyAndPolish(extracted, curated);
  }

  static List<StatusBarSettingItem> _mergeByLegacyKeyAndPolish(
    List<StatusBarSettingItem> extracted,
    List<StatusBarSettingItem> curated,
  ) {
    final curatedByKey = <String, StatusBarSettingItem>{
      for (final item in curated) item.legacyKey: item,
    };
    final merged = <StatusBarSettingItem>[];
    final seen = <String>{};

    for (final item in extracted) {
      final curatedMatch = curatedByKey[item.legacyKey];
      merged.add(_mergedItem(item, curatedMatch));
      seen.add(item.legacyKey);
    }

    for (final item in curated) {
      if (seen.contains(item.legacyKey)) {
        continue;
      }
      merged.add(item);
    }
    return merged;
  }

  static StatusBarSettingItem _mergedItem(
    StatusBarSettingItem extracted,
    StatusBarSettingItem? curated,
  ) {
    final subtitle = curated?.subtitle ?? extracted.subtitle;
    final polishedSubtitle = _isInternalSubtitle(subtitle) ? null : subtitle;
    final options = _preferOptions(extracted, curated);

    return StatusBarSettingItem(
      legacyKey: extracted.legacyKey,
      title: curated?.title ?? _polishTitle(extracted.title),
      subtitle: polishedSubtitle,
      controlType: extracted.controlType,
      group: _polishGroup(curated?.group ?? extracted.group),
      defaultValue: extracted.defaultValue,
      min: extracted.min,
      max: extracted.max,
      options: options,
      step: extracted.step,
      preferenceType: extracted.preferenceType,
      intentAction: extracted.intentAction,
      entriesReference: extracted.entriesReference,
      entryValuesReference: extracted.entryValuesReference,
      xmlReference: extracted.xmlReference,
      layoutReferences: extracted.layoutReferences,
      drawableReferences: extracted.drawableReferences,
    );
  }

  static List<StatusBarOption> _preferOptions(StatusBarSettingItem extracted, StatusBarSettingItem? curated) {
    if (curated != null && curated.options.isNotEmpty) {
      final extractedDefaultOnly = extracted.options.length == 1 && extracted.options.first.label == 'Default';
      if (extracted.options.isEmpty || extractedDefaultOnly) {
        return curated.options;
      }
    }
    return extracted.options;
  }

  static bool _isInternalSubtitle(String? subtitle) {
    if (subtitle == null || subtitle.trim().isEmpty) return false;
    final value = subtitle.toLowerCase();
    return value.contains('source-preserved') ||
        value.contains('depends on') ||
        value.contains('legacy fragment') ||
        value.contains('android.theme');
  }

  static String? _polishTitle(String? title) {
    if (title == null) return null;
    if (title == 'Android.Theme.Customization.Battery Icon') {
      return 'Battery icon theme';
    }
    return title;
  }

  static String? _polishGroup(String? group) {
    if (group == null || group.trim().isEmpty) {
      return group;
    }
    final value = group.toLowerCase();
    if (value.contains('source-preserved') || value.contains('legacy fragment') || value.contains('android.theme')) {
      return 'Advanced';
    }
    return group;
  }

  static final Map<String, List<StatusBarSettingItem>> _mapped = <String, List<StatusBarSettingItem>>{
    'resize_statusbar': MezoResizeSource.settings,
    'battery': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_bat_element_visible',
        title: 'Show battery icon',
        subtitle: 'Display battery icon in the status bar cluster',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_indicator_style',
        title: 'Battery style',
        subtitle: 'Choose global battery indicator style family',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'portrait',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Portrait capsule', value: 'portrait'),
          StatusBarOption(label: 'Landscape capsule', value: 'landscape'),
          StatusBarOption(label: 'Minimal line', value: 'line'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'use_legacy_drawable',
        title: 'Battery icon style',
        subtitle: 'Switch icon pack between modern and legacy families',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'modern',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Modern', value: 'modern'),
          StatusBarOption(label: 'Legacy', value: 'legacy'),
          StatusBarOption(label: 'Thin monochrome', value: 'mono'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_mark_enable',
        title: 'Battery percent icon',
        subtitle: 'Show percentage mark beside battery text',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupBehavior,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_style',
        title: 'Battery percent style',
        subtitle: 'Choose how percentage is rendered next to battery icon',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'outside_right',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Outside right', value: 'outside_right'),
          StatusBarOption(label: 'Outside left', value: 'outside_left'),
          StatusBarOption(label: 'Inside icon', value: 'inside'),
          StatusBarOption(label: 'Only percent', value: 'percent_only'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'batteryview_zoom',
        title: 'Icon measurements • size',
        subtitle: 'Scale battery icon size while preserving detail',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 150,
      ),
      const StatusBarSettingItem(
        legacyKey: 'batteryview_scale',
        title: 'Icon measurements • width',
        subtitle: 'Stretch or shrink icon width profile',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
      ),
      const StatusBarSettingItem(
        legacyKey: 'batteryview_division',
        title: 'Icon measurements • offset',
        subtitle: 'Move battery icon horizontally for fine positioning',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_zoom',
        title: 'Percent measurements • size',
        subtitle: 'Scale battery percentage text size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 14.0,
        min: 1,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_division',
        title: 'Percent style and position',
        subtitle: 'Adjust battery percentage spacing from the icon',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 20.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_charge_zoom',
        title: 'Charge indicator measurements • size',
        subtitle: 'Scale charging bolt and charging overlays',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 150,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_digit_zoom',
        title: 'Percentage size inside icon',
        subtitle: 'Control in-icon percentage digit size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 24.0,
        min: 1,
        max: 50,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_charge_color',
        title: 'Charge color',
        subtitle: 'Set charging indicator tint for premium contrast',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#90FFAC',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_digit_color',
        title: 'Battery percentage color and shadow',
        subtitle: 'Apply text tint and glow behavior to battery digits',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FFFFFF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_level_20_color',
        title: 'Color less than 20%',
        subtitle: 'Battery fill color for critical battery levels',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FF6E7A',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_level_40_color',
        title: 'Color less than 40%',
        subtitle: 'Battery fill color for low battery levels',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FFC66D',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_level_60_color',
        title: 'Color less than 60%',
        subtitle: 'Battery fill color for medium battery levels',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FFE98C',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_level_80_color',
        title: 'Color less than 80%',
        subtitle: 'Battery fill color for balanced battery levels',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#90FFAC',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_level_100_color',
        title: 'Color less than 100%',
        subtitle: 'Battery fill color for high battery levels',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#79E3CB',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_typefase',
        title: 'Battery font',
        subtitle: 'Select font family for battery percentage text',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupFont,
        defaultValue: 'sf_pro',
        options: <StatusBarOption>[
          StatusBarOption(label: 'SF Pro', value: 'sf_pro'),
          StatusBarOption(label: 'Inter', value: 'inter'),
          StatusBarOption(label: 'Monospace', value: 'mono'),
        ],
      ),
    ],
    'clock': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_clock_element_visible',
        title: 'Show statusbar clock',
        subtitle: 'Enable main status bar clock visibility',
        controlType: StatusBarControlType.toggle,
        group: 'Statusbar clock',
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'clock_mezo_time_style',
        title: 'Show 24-hour clock',
        subtitle: 'Use 24-hour format for status clock',
        controlType: StatusBarControlType.toggle,
        group: 'Statusbar clock',
        defaultValue: false,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_dots_enable',
        title: 'Blinking dots',
        subtitle: 'Animate colon separators while clock updates',
        controlType: StatusBarControlType.toggle,
        group: 'Statusbar clock',
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_second_enable',
        title: 'Show seconds',
        subtitle: 'Enable real-time seconds in statusbar clock',
        controlType: StatusBarControlType.toggle,
        group: 'Statusbar clock',
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_anim_style',
        title: 'Clock animation style',
        subtitle: 'Set clock transition effect on each minute change',
        controlType: StatusBarControlType.select,
        group: 'Statusbar clock',
        defaultValue: 'soft_fade',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Soft fade', value: 'soft_fade'),
          StatusBarOption(label: 'Vertical slide', value: 'slide_up'),
          StatusBarOption(label: 'Static', value: 'static'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_zoom',
        title: 'Statusbar clock size',
        subtitle: 'Scale the main clock text size',
        controlType: StatusBarControlType.slider,
        group: 'Statusbar clock',
        defaultValue: 14.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_division',
        title: 'Clock division',
        subtitle: 'Adjust spacing between clock and neighboring modules',
        controlType: StatusBarControlType.slider,
        group: 'Statusbar clock',
        defaultValue: 20.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_color',
        title: 'Clock color',
        subtitle: 'Set primary clock tint for dark glass backgrounds',
        controlType: StatusBarControlType.color,
        group: 'Statusbar clock',
        defaultValue: '#FFFFFF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_zoom',
        title: 'Size',
        subtitle: 'Scale expanded clock in notification center',
        controlType: StatusBarControlType.slider,
        group: 'Notification center clock',
        defaultValue: 50.0,
        min: 1,
        max: 100,
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_anim_style',
        title: 'Digits change animation',
        subtitle: 'Set animation style used in expanded panel clock',
        controlType: StatusBarControlType.select,
        group: 'Notification center clock',
        defaultValue: 'none',
        options: <StatusBarOption>[
          StatusBarOption(label: 'None', value: 'none'),
          StatusBarOption(label: 'Fade', value: 'fade'),
          StatusBarOption(label: 'Slide', value: 'slide'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_division',
        title: 'Division',
        subtitle: 'Adjust spacing around expanded clock block',
        controlType: StatusBarControlType.slider,
        group: 'Notification center clock',
        defaultValue: 18.0,
        min: 0,
        max: 40,
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_second_enable',
        title: 'Show seconds',
        subtitle: 'Include seconds in expanded notification center clock',
        controlType: StatusBarControlType.toggle,
        group: 'Notification center clock',
        defaultValue: false,
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_dots_enable',
        title: 'Blinking dots',
        subtitle: 'Animate separators in expanded clock',
        controlType: StatusBarControlType.toggle,
        group: 'Notification center clock',
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_color',
        title: 'Color',
        subtitle: 'Set notification center clock color',
        controlType: StatusBarControlType.color,
        group: 'Notification center clock',
        defaultValue: '#FFFFFF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_format',
        title: 'Date format selector',
        subtitle: 'Pick date format used in notification header',
        controlType: StatusBarControlType.select,
        group: 'Date style',
        defaultValue: 'EEE, dd MMM',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Wed, 22 Apr', value: 'EEE, dd MMM'),
          StatusBarOption(label: '22/04/2026', value: 'dd/MM/yyyy'),
          StatusBarOption(label: 'April 22', value: 'MMMM d'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_zoom',
        title: 'Size',
        subtitle: 'Scale date row text size for notification header',
        controlType: StatusBarControlType.slider,
        group: 'Date style',
        defaultValue: 18.0,
        min: 1,
        max: 70,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_division',
        title: 'Division',
        subtitle: 'Adjust spacing around date block',
        controlType: StatusBarControlType.slider,
        group: 'Date style',
        defaultValue: 18.0,
        min: 0,
        max: 40,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_color',
        title: 'Color',
        subtitle: 'Set date text color in notification center',
        controlType: StatusBarControlType.color,
        group: 'Date style',
        defaultValue: '#FFFFFF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_font',
        title: 'Font',
        subtitle: 'Pick dedicated date block font family',
        controlType: StatusBarControlType.select,
        group: 'Date style',
        defaultValue: 'sf_pro',
        options: <StatusBarOption>[
          StatusBarOption(label: 'SF Pro', value: 'sf_pro'),
          StatusBarOption(label: 'Inter', value: 'inter'),
          StatusBarOption(label: 'DIN', value: 'din'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'weather_notif_text_zoom',
        title: 'Size',
        subtitle: 'Set weather text size in notification center area',
        controlType: StatusBarControlType.slider,
        group: 'Weather block',
        defaultValue: 16.0,
        min: 5,
        max: 20,
      ),
      const StatusBarSettingItem(
        legacyKey: 'weather_notif_text_color',
        title: 'Color',
        subtitle: 'Set weather text tint in notification center',
        controlType: StatusBarControlType.color,
        group: 'Weather block',
        defaultValue: '#8DE8FF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'weather_notif_text_font',
        title: 'Font',
        subtitle: 'Choose weather label font family',
        controlType: StatusBarControlType.select,
        group: 'Weather block',
        defaultValue: 'inter',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Inter', value: 'inter'),
          StatusBarOption(label: 'SF Pro', value: 'sf_pro'),
          StatusBarOption(label: 'Roboto', value: 'roboto'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'Settingsfachen_zoom',
        title: 'Size',
        subtitle: 'Scale settings icon block used beside clock and date',
        controlType: StatusBarControlType.slider,
        group: 'Settings icon block',
        defaultValue: 130.0,
        min: 50,
        max: 200,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Settingsfachen_scale',
        title: 'Scale',
        subtitle: 'Adjust icon block width scale in notification center',
        controlType: StatusBarControlType.slider,
        group: 'Settings icon block',
        defaultValue: 100.0,
        min: 50,
        max: 180,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Settingsfachen_division',
        title: 'Division',
        subtitle: 'Set spacing around settings icon block',
        controlType: StatusBarControlType.slider,
        group: 'Settings icon block',
        defaultValue: 18.0,
        min: 0,
        max: 40,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Settingsfachen_color',
        title: 'Color',
        subtitle: 'Choose tint color for the settings icon block',
        controlType: StatusBarControlType.color,
        group: 'Settings icon block',
        defaultValue: '#FFFFFF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_typefase',
        title: 'Clock font',
        subtitle: 'Pick typography family for status and expanded clock',
        controlType: StatusBarControlType.select,
        group: 'Statusbar clock',
        defaultValue: 'sf_pro',
        options: <StatusBarOption>[
          StatusBarOption(label: 'SF Pro', value: 'sf_pro'),
          StatusBarOption(label: 'Inter', value: 'inter'),
          StatusBarOption(label: 'DIN', value: 'din'),
        ],
      ),
    ],
    'netspeed': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'status_bar_show_network_speed',
        title: 'Netspeed style',
        subtitle: 'Choose how netspeed text is displayed in the status bar',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupVisibility,
        defaultValue: '1',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Do not show', value: '0'),
          StatusBarOption(label: 'One line', value: '1'),
          StatusBarOption(label: 'Two lines', value: '2'),
          StatusBarOption(label: 'Default', value: '3'),
        ],
        intentAction: '',
        entriesReference: '@array/net_speed_entries',
        entryValuesReference: '@array/net_speed_values',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'net_speed_zoom',
        title: 'Netspeed text size',
        subtitle: 'Scale network speed text in statusbar',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 12.0,
        min: 1,
        max: 70,
        intentAction: 'my.settings.intent.net_speed_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'net_speed_division',
        title: 'Netspeed spacing',
        subtitle: 'Set horizontal spacing around speed label',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 20.0,
        min: 0,
        max: 30,
        intentAction: 'my.settings.intent.net_speed_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'net_speed_height',
        title: 'Vertical height',
        subtitle: 'Adjust vertical position of the netspeed text',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 50.0,
        min: 30,
        max: 150,
        intentAction: 'my.settings.intent.net_speed_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_bar_network_speed_interval',
        title: 'Refresh interval',
        subtitle: 'Set update interval for netspeed in milliseconds',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupBehavior,
        defaultValue: 1000.0,
        min: 500,
        max: 4000,
        step: 500,
        intentAction: '',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'net_speed_color',
        title: 'Netspeed color',
        subtitle: 'Set text color for network speed indicator',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#00000000',
        intentAction: 'my.settings.intent.net_speed_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'net_speed_typefase',
        title: 'Netspeed font',
        subtitle: 'Choose a custom font or keep Default',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupTypography,
        defaultValue: 'Default',
        intentAction: 'my.settings.intent.net_speed_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/speed_elite.smali',
      ),
    ],
    'network': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_net_element_visible',
        title: 'Show SIM icons',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
        intentAction: 'my.settings.intent.element_visibility_change.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_2.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'elem_wifi_element_visible',
        title: 'Show Wi-Fi icon',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
        intentAction: 'my.settings.intent.element_visibility_change.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_2.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'vpn_visible',
        title: 'Show VoLTE / VPN icon',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
        intentAction: 'my.settings.intent.vpn_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_2.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'vowifi_visible',
        title: 'Show VoWiFi icon',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
        intentAction: 'my.settings.intent.vowifi_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_2.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'roam_visible',
        title: 'Show roaming icon',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
        intentAction: 'my.settings.intent.roam_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_2.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'sim_one_color',
        title: 'SIM 1 color',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.sim_zoom.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_1.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'sim_two_color',
        title: 'SIM 2 color',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.sim_zoom.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_1.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'wifiview_color',
        title: 'Wi-Fi color',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.wifiview_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_1.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'airplaneview_color',
        title: 'Wi-Fi arrows color',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.airplaneview_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_1.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_type_color',
        title: 'Network type color',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.mobile_type_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_1.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_inout_color',
        title: 'Network arrows color',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.mobile_inout_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_1.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'vpn_color',
        title: 'VoLTE / VPN color',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.vpn_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_1.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'vowifi_color',
        title: 'VoWiFi color',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.vowifi_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_1.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'roam_color',
        title: 'Roaming color',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.roam_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elite_net_frag_1.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'simview_zoom',
        title: 'SIM icons size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.sim_zoom.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'simview_scale',
        title: 'SIM icons scale',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.sim_zoom.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'simview_division',
        title: 'SIM icons spacing',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
        intentAction: 'my.settings.intent.sim_zoom.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_type_zoom',
        title: 'Network type size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 20.0,
        min: 1,
        max: 70,
        intentAction: 'my.settings.intent.mobile_type_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_type_division',
        title: 'Network type spacing',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 10.0,
        min: -30,
        max: 30,
        intentAction: 'my.settings.intent.mobile_type_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_inout_zoom',
        title: 'Network arrows size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.mobile_inout_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_inout_scale',
        title: 'Network arrows scale',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.mobile_inout_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_inout_division',
        title: 'Network arrows spacing',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
        intentAction: 'my.settings.intent.mobile_inout_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_net_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'wifiview_zoom',
        title: 'Wi-Fi size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.wifiview_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_wifi_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'wifiview_scale',
        title: 'Wi-Fi scale',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.wifiview_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_wifi_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'wifiview_division',
        title: 'Wi-Fi spacing',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
        intentAction: 'my.settings.intent.wifiview_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_wifi_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'airplaneview_zoom',
        title: 'Wi-Fi arrows size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.airplaneview_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_wifi_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'airplaneview_scale',
        title: 'Wi-Fi arrows scale',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.airplaneview_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_wifi_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'airplaneview_division',
        title: 'Wi-Fi arrows spacing',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
        intentAction: 'my.settings.intent.airplaneview_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_wifi_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'vpn_zoom',
        title: 'VoLTE / VPN size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.vpn_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_volte_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'vpn_scale',
        title: 'VoLTE / VPN scale',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.vpn_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_volte_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'vpn_division',
        title: 'VoLTE / VPN spacing',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
        intentAction: 'my.settings.intent.vpn_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_volte_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'vowifi_zoom',
        title: 'VoWiFi size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.vowifi_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_vowifi_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'vowifi_scale',
        title: 'VoWiFi scale',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.vowifi_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_vowifi_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'vowifi_division',
        title: 'VoWiFi spacing',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
        intentAction: 'my.settings.intent.vowifi_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_vowifi_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'roam_zoom',
        title: 'Roaming size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.roam_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_roam_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'roam_scale',
        title: 'Roaming scale',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
        intentAction: 'my.settings.intent.roam_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_roam_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'roam_division',
        title: 'Roaming spacing',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
        intentAction: 'my.settings.intent.roam_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/elem_roam_elite.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_type_typefase',
        title: 'Network type font',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupFont,
        defaultValue: 'Default',
        intentAction: 'my.settings.intent.mobile_type_color.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_icon_colors.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'elem_net1_rotate',
        title: 'Rotate SIM 1 icon',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupRotation,
        defaultValue: true,
        intentAction: 'my.settings.intent.elem_net1_rotate.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_icon_colors.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'elem_net2_rotate',
        title: 'Rotate SIM 2 icon',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupRotation,
        defaultValue: false,
        intentAction: 'my.settings.intent.elem_net2_rotate.CHANGE',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_icon_colors.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'sim_type_position',
        title: 'Horizontal network type',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupBehavior,
        defaultValue: true,
        intentAction: '',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_icon_colors.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'sim_type_margin',
        title: 'SIM and data icon margin',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: -20.0,
        min: -100,
        max: 50,
        intentAction: '',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_icon_colors.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'android.theme.customization.signal_icon',
        title: 'Signal icon style',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupBehavior,
        defaultValue: 'com.android.systemui',
        intentAction: 'my.intent.action.REFRESH_SYSTEMUI',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_icon_colors.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'android.theme.customization.wifi_icon',
        title: 'Wi-Fi icon style',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupBehavior,
        defaultValue: 'com.android.systemui',
        intentAction: 'my.intent.action.REFRESH_SYSTEMUI',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_icon_colors.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'android.theme.customization.vowifi_icon',
        title: 'VoWiFi icon style',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupBehavior,
        defaultValue: 'com.android.systemui',
        intentAction: 'my.intent.action.REFRESH_SYSTEMUI',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_icon_colors.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'android.theme.customization.volte_icon',
        title: 'VoLTE icon style',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupBehavior,
        defaultValue: 'com.android.systemui',
        intentAction: 'my.intent.action.REFRESH_SYSTEMUI',
        xmlReference: 'reference/mezo/mezo/res/xml/statusbar_icon_colors.smali',
      ),
    ],
    'notification_icons': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'reverse_notification_sorting_order',
        title: 'Reverse notification order',
        subtitle: 'Reverse icon ordering in the statusbar cluster.',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupBehavior,
        defaultValue: false,
        intentAction: 'my.settings.intent.notif_icon_color.CHANGE',
        preferenceType: 'XMiuiCheckBoxPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_notif.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_color',
        title: 'Notification icon color',
        subtitle: 'ARGB color with transparency support.',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: 0x00000000,
        intentAction: 'my.settings.intent.notif_icon_color.CHANGE',
        preferenceType: 'XMiuiColorPickerPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_notif.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_zoom',
        title: 'Notification icon size',
        subtitle: 'Controls icon zoom amount.',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 100.0,
        min: 10,
        max: 150,
        intentAction: 'my.settings.intent.notif_icon_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_notif.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_scale',
        title: 'Notification icon scale',
        subtitle: 'Controls icon scale amount.',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 100.0,
        min: 0,
        max: 150,
        intentAction: 'my.settings.intent.notif_icon_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_notif.smali',
      ),
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_division',
        title: 'Notification icon spacing',
        subtitle: 'Controls distance between icons.',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
        intentAction: 'my.settings.intent.notif_icon_color.CHANGE',
        preferenceType: 'EdSeekBarPreference',
        xmlReference: 'reference/mezo/mezo/res/xml/settings_notif.smali',
      ),
    ],
    'status_icons': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_status_element_visible',
        title: 'Show status icons',
        subtitle: 'Display utility icons like Bluetooth and alarm',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_icon_zoom',
        title: 'Status icon size',
        subtitle: 'Scale utility icon size group-wide',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 100.0,
        min: 50,
        max: 200,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_icon_scale',
        title: 'Status icon scale',
        subtitle: 'Adjust icon scale for utility indicators',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 100.0,
        min: 50,
        max: 150,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_icon_division',
        title: 'Status icon spacing',
        subtitle: 'Control spacing between utility icons',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_icon_color',
        title: 'Status icon color',
        subtitle: 'Choose tint used by status utility icons',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FFFFFF',
      ),
    ],
    'date': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_date_element_visible',
        title: 'Show date',
        subtitle: 'Display date label in statusbar row',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: false,
      ),
      const StatusBarSettingItem(
        legacyKey: 'statusbar_date_format',
        title: 'Date format',
        subtitle: 'Pick date format pattern for the status area',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupTypography,
        defaultValue: 'EEE, dd MMM',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Wed, 22 Apr', value: 'EEE, dd MMM'),
          StatusBarOption(label: '22/04/2026', value: 'dd/MM/yyyy'),
          StatusBarOption(label: 'April 22', value: 'MMMM d'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_date_zoom',
        title: 'Date text size',
        subtitle: 'Scale date text for better balance with clock',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 10.0,
        min: 1,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_date_division',
        title: 'Date spacing',
        subtitle: 'Adjust spacing around the date label',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 20.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_date_color',
        title: 'Date color',
        subtitle: 'Set date text color for contrast and depth',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#B7C6FF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_date_typefase',
        title: 'Date font',
        subtitle: 'Choose statusbar date font family',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupTypography,
        defaultValue: 'Default',
      ),
    ],
    'weather': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_weather_element_visible',
        title: 'Show weather',
        subtitle: 'Display weather status in statusbar area',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'weather_anim_enable',
        title: 'Weather animation',
        subtitle: 'Enable subtle weather icon animation',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupAnimation,
        defaultValue: false,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_weather_zoom',
        title: 'Weather size',
        subtitle: 'Scale weather text and icon group',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 16.0,
        min: 1,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_weather_division',
        title: 'Weather spacing',
        subtitle: 'Control weather group spacing from adjacent items',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 20.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_weather_color',
        title: 'Weather color',
        subtitle: 'Set weather icon and text tint',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#8DE8FF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_weather_typefase',
        title: 'Weather font',
        subtitle: 'Choose weather label font family',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupTypography,
        defaultValue: 'Default',
      ),
    ],
    'prompt_icon': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_prompt_scale',
        title: 'Prompt size',
        subtitle: 'Scale prompt icon size for subtle or strong presence',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 75.0,
        min: 50,
        max: 150,
      ),
      const StatusBarSettingItem(
        legacyKey: 'elem_prompt_division',
        title: 'Prompt offset',
        subtitle: 'Move prompt icon horizontally for alignment',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
      ),
    ],
    'background': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'bg_clock',
        title: 'Clock background',
        subtitle: 'Customize background plate behind clock',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_battery',
        title: 'Battery background',
        subtitle: 'Set background style for battery element',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_sim1',
        title: 'SIM 1 background',
        subtitle: 'Set background for primary SIM indicator',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_sim2',
        title: 'SIM 2 background',
        subtitle: 'Set background for secondary SIM indicator',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_wifi',
        title: 'Wi-Fi background',
        subtitle: 'Customize background card behind Wi-Fi icon',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_speed',
        title: 'Network speed background',
        subtitle: 'Configure background for network speed text',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_notif',
        title: 'Notification icon background',
        subtitle: 'Set background for notification icon stack',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_status',
        title: 'Status icon background',
        subtitle: 'Set background plate for utility icons',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_weather',
        title: 'Weather background',
        subtitle: 'Customize weather element background layer',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_date',
        title: 'Date background',
        subtitle: 'Set background for date text element',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_prompt',
        title: 'Prompt icon background',
        subtitle: 'Set background for prompt icon plate',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
    ],
  };
}
