import 'package:deadzon/features/statusbar/statusbar_models.dart';
import 'package:deadzon/features/statusbar/statusbar_strings.dart';

class StatusBarMapper {
  const StatusBarMapper._();

  static List<StatusBarSettingItem> settingsForSection(String sectionId) {
    return _mapped[sectionId] ?? const <StatusBarSettingItem>[];
  }

  static final Map<String, List<StatusBarSettingItem>> _mapped = <String, List<StatusBarSettingItem>>{
    'resize_statusbar': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'status_bar_elem_center_in_island',
        title: 'Show center element while island is open',
        subtitle: 'Keeps center content visible when dynamic island expands',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'custom_status_bar_top',
        title: 'Top margin',
        subtitle: 'Push status content slightly downward for alignment',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 2.0,
        min: 0,
        max: 40,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_bar_element_cutout_type',
        title: 'Cutout placement mode',
        subtitle: 'Choose how elements react around camera cutout',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupLayout,
        defaultValue: 'balanced',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Balanced', value: 'balanced'),
          StatusBarOption(label: 'Center preferred', value: 'center'),
          StatusBarOption(label: 'Left preferred', value: 'left'),
        ],
      ),
    ],
    'battery': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_bat_element_visible',
        title: 'Show battery element',
        subtitle: 'Display battery icon in the status bar area',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'batteryview_zoom',
        title: 'Battery icon scale',
        subtitle: 'Resize battery icon while preserving clarity',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 100.0,
        min: 50,
        max: 150,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_indicator_style',
        title: 'Battery icon style',
        subtitle: 'Switch among Mezo battery indicator styles',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'portrait',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Portrait capsule', value: 'portrait'),
          StatusBarOption(label: 'Landscape capsule', value: 'landscape'),
          StatusBarOption(label: 'Minimal line', value: 'line'),
        ],
      ),
    ],
    'clock': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'status_clock_second_enable',
        title: 'Show seconds',
        subtitle: 'Add real-time seconds to the status clock',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupBehavior,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_zoom',
        title: 'Clock text size',
        subtitle: 'Adjust main clock size for readability',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 14.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_anim_style',
        title: 'Clock motion style',
        subtitle: 'Set how time transitions animate on change',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupAnimation,
        defaultValue: 'soft_fade',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Soft fade', value: 'soft_fade'),
          StatusBarOption(label: 'Slide up', value: 'slide_up'),
          StatusBarOption(label: 'Static', value: 'static'),
        ],
      ),
    ],
    'netspeed': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_speed_visible',
        title: 'Show network speed',
        subtitle: 'Display upload and download speed in status bar',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'elem_speed_zoom',
        title: 'Speed label size',
        subtitle: 'Scale traffic text to match status bar density',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 14.0,
        min: 8,
        max: 24,
      ),
      const StatusBarSettingItem(
        legacyKey: 'elem_speed_color',
        title: 'Speed accent color',
        subtitle: 'Choose color for network speed indicator',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#8DE8FF',
      ),
    ],
    'network': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_net_visible',
        title: 'Show network icons',
        subtitle: 'Keep Wi-Fi and cellular signals in the top bar',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'elem_net_style',
        title: 'Signal icon family',
        subtitle: 'Pick icon language for network strength display',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'classic',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Classic', value: 'classic'),
          StatusBarOption(label: 'Rounded', value: 'rounded'),
          StatusBarOption(label: 'Minimal', value: 'minimal'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'elem_net_padding',
        title: 'Signal spacing',
        subtitle: 'Adjust spacing between Wi-Fi and mobile indicators',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 12.0,
        min: 0,
        max: 30,
      ),
    ],
    'notification_icons': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_enable',
        title: 'Show notification icons',
        subtitle: 'Display app notifications on the status line',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_limit',
        title: 'Visible icon count',
        subtitle: 'Set max notification icons before overflow dot',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupBehavior,
        defaultValue: 4.0,
        min: 1,
        max: 10,
      ),
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_tint',
        title: 'Notification tint',
        subtitle: 'Tint all status notification icons together',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FFFFFF',
      ),
    ],
    'status_icons': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'status_icon_manager_enable',
        title: 'Enable status icon manager',
        subtitle: 'Manage Bluetooth, alarm, headset, and location icons',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupBehavior,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_icon_size',
        title: 'Status icon size',
        subtitle: 'Scale utility icons without changing layout rhythm',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 100.0,
        min: 70,
        max: 150,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_icon_profile',
        title: 'Icon profile',
        subtitle: 'Choose normal, compact, or ultra-minimal profile',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'normal',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Normal', value: 'normal'),
          StatusBarOption(label: 'Compact', value: 'compact'),
          StatusBarOption(label: 'Ultra-minimal', value: 'minimal'),
        ],
      ),
    ],
    'date': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_format',
        title: 'Date format',
        subtitle: 'Select readable date pattern for the status area',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupTypography,
        defaultValue: 'EEE, dd MMM',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Wed, 22 Apr', value: 'EEE, dd MMM'),
          StatusBarOption(label: '22/04/2026', value: 'dd/MM/yyyy'),
          StatusBarOption(label: 'April 22', value: 'MMMM d'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_zoom',
        title: 'Date text size',
        subtitle: 'Scale date to match your status typography',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 18.0,
        min: 10,
        max: 70,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_color',
        title: 'Date color',
        subtitle: 'Set accent color for date string',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#B7C6FF',
      ),
    ],
    'weather': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'weather_notif_enable',
        title: 'Show weather text',
        subtitle: 'Display current condition beside status elements',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'weather_notif_text_zoom',
        title: 'Weather text size',
        subtitle: 'Make weather label smaller or larger',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 16.0,
        min: 5,
        max: 20,
      ),
      const StatusBarSettingItem(
        legacyKey: 'weather_icon_style',
        title: 'Weather icon style',
        subtitle: 'Use outlined, filled, or monochrome icon style',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'outlined',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Outlined', value: 'outlined'),
          StatusBarOption(label: 'Filled', value: 'filled'),
          StatusBarOption(label: 'Monochrome', value: 'mono'),
        ],
      ),
    ],
    'prompt_icon': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'statusbar_prompt_enable',
        title: 'Show prompt icon',
        subtitle: 'Enable prompt icon in the status bar cluster',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'statusbar_prompt_scale',
        title: 'Prompt icon scale',
        subtitle: 'Scale prompt icon for subtle or bold presence',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 100.0,
        min: 70,
        max: 160,
      ),
      const StatusBarSettingItem(
        legacyKey: 'statusbar_prompt_color',
        title: 'Prompt icon color',
        subtitle: 'Apply a custom accent tint to prompt icon',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#E2B4FF',
      ),
    ],
    'background': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'statusbar_background_enable',
        title: 'Enable status backdrop',
        subtitle: 'Render a subtle panel behind status elements',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupBackground,
        defaultValue: false,
      ),
      const StatusBarSettingItem(
        legacyKey: 'statusbar_background_blur',
        title: 'Backdrop blur strength',
        subtitle: 'Tune blur to blend with glass layers',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupBackground,
        defaultValue: 18.0,
        min: 0,
        max: 40,
      ),
      const StatusBarSettingItem(
        legacyKey: 'statusbar_background_tint',
        title: 'Backdrop tint color',
        subtitle: 'Colorize backdrop to match your Mezo palette',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
    ],
  };
}
