import 'package:deadzon/features/statusbar/data/mezo_resize_source.dart';
import 'package:deadzon/features/statusbar/statusbar_models.dart';
import 'package:deadzon/features/statusbar/statusbar_source_inventory.dart';
import 'package:deadzon/features/statusbar/statusbar_strings.dart';

class StatusBarMapper {
  const StatusBarMapper._();

  static List<StatusBarSettingItem> settingsForSection(String sectionId) {
    final curated = _mapped[sectionId] ?? const <StatusBarSettingItem>[];
    final extracted = StatusbarSourceInventory.extractedBySection[sectionId] ?? const <StatusBarSettingItem>[];
    if (extracted.isEmpty) {
      return curated;
    }
    return _mergeByLegacyKey(curated, extracted);
  }

  static List<StatusBarSettingItem> _mergeByLegacyKey(
    List<StatusBarSettingItem> curated,
    List<StatusBarSettingItem> extracted,
  ) {
    final seen = <String>{};
    final merged = <StatusBarSettingItem>[];
    for (final item in curated) {
      merged.add(item);
      seen.add(item.legacyKey);
    }
    for (final item in extracted) {
      if (seen.contains(item.legacyKey)) {
        continue;
      }
      merged.add(item);
    }
    return merged;
  }

  static final Map<String, List<StatusBarSettingItem>> _mapped = <String, List<StatusBarSettingItem>>{
    'resize_statusbar': MezoResizeSource.settings,
    'battery': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_bat_element_visible',
        title: 'Show battery icon',
        subtitle: 'Display battery icon in the status bar cluster',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_indicator_style',
        title: 'Battery style',
        subtitle: 'Choose global battery indicator style family',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'portrait',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Portrait capsule', value: 'portrait'),
          StatusBarOption(label: 'Landscape capsule', value: 'landscape'),
          StatusBarOption(label: 'Minimal line', value: 'line'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'use_legacy_drawable',
        title: 'Battery icon style',
        subtitle: 'Switch icon pack between modern and legacy families',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'modern',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Modern', value: 'modern'),
          StatusBarOption(label: 'Legacy', value: 'legacy'),
          StatusBarOption(label: 'Thin monochrome', value: 'mono'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_mark_enable',
        title: 'Battery percent icon',
        subtitle: 'Show percentage mark beside battery text',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupBehavior,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_style',
        title: 'Battery percent style',
        subtitle: 'Choose how percentage is rendered next to battery icon',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'outside_right',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Outside right', value: 'outside_right'),
          StatusBarOption(label: 'Outside left', value: 'outside_left'),
          StatusBarOption(label: 'Inside icon', value: 'inside'),
          StatusBarOption(label: 'Only percent', value: 'percent_only'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'batteryview_zoom',
        title: 'Icon measurements • size',
        subtitle: 'Scale battery icon size while preserving detail',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 150,
      ),
      const StatusBarSettingItem(
        legacyKey: 'batteryview_scale',
        title: 'Icon measurements • width',
        subtitle: 'Stretch or shrink icon width profile',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
      ),
      const StatusBarSettingItem(
        legacyKey: 'batteryview_division',
        title: 'Icon measurements • offset',
        subtitle: 'Move battery icon horizontally for fine positioning',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_zoom',
        title: 'Percent measurements • size',
        subtitle: 'Scale battery percentage text size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 14.0,
        min: 1,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_division',
        title: 'Percent style and position',
        subtitle: 'Adjust battery percentage spacing from the icon',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 20.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_charge_zoom',
        title: 'Charge indicator measurements • size',
        subtitle: 'Scale charging bolt and charging overlays',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 150,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_digit_zoom',
        title: 'Percentage size inside icon',
        subtitle: 'Control in-icon percentage digit size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 24.0,
        min: 1,
        max: 50,
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_charge_color',
        title: 'Charge color',
        subtitle: 'Set charging indicator tint for premium contrast',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#90FFAC',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_digit_color',
        title: 'Battery percentage color and shadow',
        subtitle: 'Apply text tint and glow behavior to battery digits',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FFFFFF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_level_20_color',
        title: 'Color less than 20%',
        subtitle: 'Battery fill color for critical battery levels',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FF6E7A',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_level_40_color',
        title: 'Color less than 40%',
        subtitle: 'Battery fill color for low battery levels',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FFC66D',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_level_60_color',
        title: 'Color less than 60%',
        subtitle: 'Battery fill color for medium battery levels',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FFE98C',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_level_80_color',
        title: 'Color less than 80%',
        subtitle: 'Battery fill color for balanced battery levels',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#90FFAC',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_level_100_color',
        title: 'Color less than 100%',
        subtitle: 'Battery fill color for high battery levels',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#79E3CB',
      ),
      const StatusBarSettingItem(
        legacyKey: 'battery_percent_typefase',
        title: 'Battery font',
        subtitle: 'Select font family for battery percentage text',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupFont,
        defaultValue: 'sf_pro',
        options: <StatusBarOption>[
          StatusBarOption(label: 'SF Pro', value: 'sf_pro'),
          StatusBarOption(label: 'Inter', value: 'inter'),
          StatusBarOption(label: 'Monospace', value: 'mono'),
        ],
      ),
    ],
    'clock': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_clock_element_visible',
        title: 'Show statusbar clock',
        subtitle: 'Enable main status bar clock visibility',
        controlType: StatusBarControlType.toggle,
        group: 'Statusbar clock',
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'clock_mezo_time_style',
        title: 'Show 24-hour clock',
        subtitle: 'Use 24-hour format for status clock',
        controlType: StatusBarControlType.toggle,
        group: 'Statusbar clock',
        defaultValue: false,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_dots_enable',
        title: 'Blinking dots',
        subtitle: 'Animate colon separators while clock updates',
        controlType: StatusBarControlType.toggle,
        group: 'Statusbar clock',
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_second_enable',
        title: 'Show seconds',
        subtitle: 'Enable real-time seconds in statusbar clock',
        controlType: StatusBarControlType.toggle,
        group: 'Statusbar clock',
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_anim_style',
        title: 'Clock animation style',
        subtitle: 'Set clock transition effect on each minute change',
        controlType: StatusBarControlType.select,
        group: 'Statusbar clock',
        defaultValue: 'soft_fade',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Soft fade', value: 'soft_fade'),
          StatusBarOption(label: 'Vertical slide', value: 'slide_up'),
          StatusBarOption(label: 'Static', value: 'static'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_zoom',
        title: 'Statusbar clock size',
        subtitle: 'Scale the main clock text size',
        controlType: StatusBarControlType.slider,
        group: 'Statusbar clock',
        defaultValue: 14.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_division',
        title: 'Clock division',
        subtitle: 'Adjust spacing between clock and neighboring modules',
        controlType: StatusBarControlType.slider,
        group: 'Statusbar clock',
        defaultValue: 20.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_color',
        title: 'Clock color',
        subtitle: 'Set primary clock tint for dark glass backgrounds',
        controlType: StatusBarControlType.color,
        group: 'Statusbar clock',
        defaultValue: '#FFFFFF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_zoom',
        title: 'Size',
        subtitle: 'Scale expanded clock in notification center',
        controlType: StatusBarControlType.slider,
        group: 'Notification center clock',
        defaultValue: 50.0,
        min: 1,
        max: 100,
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_anim_style',
        title: 'Digits change animation',
        subtitle: 'Set animation style used in expanded panel clock',
        controlType: StatusBarControlType.select,
        group: 'Notification center clock',
        defaultValue: 'none',
        options: <StatusBarOption>[
          StatusBarOption(label: 'None', value: 'none'),
          StatusBarOption(label: 'Fade', value: 'fade'),
          StatusBarOption(label: 'Slide', value: 'slide'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_division',
        title: 'Division',
        subtitle: 'Adjust spacing around expanded clock block',
        controlType: StatusBarControlType.slider,
        group: 'Notification center clock',
        defaultValue: 18.0,
        min: 0,
        max: 40,
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_second_enable',
        title: 'Show seconds',
        subtitle: 'Include seconds in expanded notification center clock',
        controlType: StatusBarControlType.toggle,
        group: 'Notification center clock',
        defaultValue: false,
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_dots_enable',
        title: 'Blinking dots',
        subtitle: 'Animate separators in expanded clock',
        controlType: StatusBarControlType.toggle,
        group: 'Notification center clock',
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'expanded_clock_color',
        title: 'Color',
        subtitle: 'Set notification center clock color',
        controlType: StatusBarControlType.color,
        group: 'Notification center clock',
        defaultValue: '#FFFFFF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_format',
        title: 'Date format selector',
        subtitle: 'Pick date format used in notification header',
        controlType: StatusBarControlType.select,
        group: 'Date style',
        defaultValue: 'EEE, dd MMM',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Wed, 22 Apr', value: 'EEE, dd MMM'),
          StatusBarOption(label: '22/04/2026', value: 'dd/MM/yyyy'),
          StatusBarOption(label: 'April 22', value: 'MMMM d'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_zoom',
        title: 'Size',
        subtitle: 'Scale date row text size for notification header',
        controlType: StatusBarControlType.slider,
        group: 'Date style',
        defaultValue: 18.0,
        min: 1,
        max: 70,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_division',
        title: 'Division',
        subtitle: 'Adjust spacing around date block',
        controlType: StatusBarControlType.slider,
        group: 'Date style',
        defaultValue: 18.0,
        min: 0,
        max: 40,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_color',
        title: 'Color',
        subtitle: 'Set date text color in notification center',
        controlType: StatusBarControlType.color,
        group: 'Date style',
        defaultValue: '#FFFFFF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'Notif_date_font',
        title: 'Font',
        subtitle: 'Pick dedicated date block font family',
        controlType: StatusBarControlType.select,
        group: 'Date style',
        defaultValue: 'sf_pro',
        options: <StatusBarOption>[
          StatusBarOption(label: 'SF Pro', value: 'sf_pro'),
          StatusBarOption(label: 'Inter', value: 'inter'),
          StatusBarOption(label: 'DIN', value: 'din'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'weather_notif_text_zoom',
        title: 'Size',
        subtitle: 'Set weather text size in notification center area',
        controlType: StatusBarControlType.slider,
        group: 'Weather block',
        defaultValue: 16.0,
        min: 5,
        max: 20,
      ),
      const StatusBarSettingItem(
        legacyKey: 'weather_notif_text_color',
        title: 'Color',
        subtitle: 'Set weather text tint in notification center',
        controlType: StatusBarControlType.color,
        group: 'Weather block',
        defaultValue: '#8DE8FF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'weather_notif_text_font',
        title: 'Font',
        subtitle: 'Choose weather label font family',
        controlType: StatusBarControlType.select,
        group: 'Weather block',
        defaultValue: 'inter',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Inter', value: 'inter'),
          StatusBarOption(label: 'SF Pro', value: 'sf_pro'),
          StatusBarOption(label: 'Roboto', value: 'roboto'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'Settingsfachen_zoom',
        title: 'Size',
        subtitle: 'Scale settings icon block used beside clock and date',
        controlType: StatusBarControlType.slider,
        group: 'Settings icon block',
        defaultValue: 130.0,
        min: 50,
        max: 200,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Settingsfachen_scale',
        title: 'Scale',
        subtitle: 'Adjust icon block width scale in notification center',
        controlType: StatusBarControlType.slider,
        group: 'Settings icon block',
        defaultValue: 100.0,
        min: 50,
        max: 180,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Settingsfachen_division',
        title: 'Division',
        subtitle: 'Set spacing around settings icon block',
        controlType: StatusBarControlType.slider,
        group: 'Settings icon block',
        defaultValue: 18.0,
        min: 0,
        max: 40,
      ),
      const StatusBarSettingItem(
        legacyKey: 'Settingsfachen_color',
        title: 'Color',
        subtitle: 'Choose tint color for the settings icon block',
        controlType: StatusBarControlType.color,
        group: 'Settings icon block',
        defaultValue: '#FFFFFF',
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_clock_typefase',
        title: 'Clock font',
        subtitle: 'Pick typography family for status and expanded clock',
        controlType: StatusBarControlType.select,
        group: 'Statusbar clock',
        defaultValue: 'sf_pro',
        options: <StatusBarOption>[
          StatusBarOption(label: 'SF Pro', value: 'sf_pro'),
          StatusBarOption(label: 'Inter', value: 'inter'),
          StatusBarOption(label: 'DIN', value: 'din'),
        ],
      ),
    ],
    'netspeed': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'status_bar_show_network_speed',
        title: 'Network speed mode',
        subtitle: 'Choose upload/download display mode',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupVisibility,
        defaultValue: 'both',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Upload + download', value: 'both'),
          StatusBarOption(label: 'Download only', value: 'down_only'),
          StatusBarOption(label: 'Hidden', value: 'hidden'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'net_speed_zoom',
        title: 'Netspeed text size',
        subtitle: 'Scale network speed text in statusbar',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 12.0,
        min: 1,
        max: 70,
      ),
      const StatusBarSettingItem(
        legacyKey: 'net_speed_division',
        title: 'Netspeed spacing',
        subtitle: 'Set horizontal spacing around speed label',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 20.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_bar_network_speed_interval',
        title: 'Refresh interval',
        subtitle: 'Control update frequency for live speed readout',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupBehavior,
        defaultValue: 1000.0,
        min: 500,
        max: 4000,
      ),
      const StatusBarSettingItem(
        legacyKey: 'net_speed_color',
        title: 'Netspeed color',
        subtitle: 'Set text color for network speed indicator',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#8DE8FF',
      ),
    ],
    'network': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_net_visible',
        title: 'Show network icons',
        subtitle: 'Enable network icon cluster in status bar',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'network_colors_enable',
        title: 'Custom network colors',
        subtitle: 'Use custom tint colors for network indicators',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupColor,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'sim_signal_style',
        title: 'Signals icon style',
        subtitle: 'Choose cellular signal icon appearance',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'filled',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Filled', value: 'filled'),
          StatusBarOption(label: 'Outlined', value: 'outlined'),
          StatusBarOption(label: 'Minimal', value: 'minimal'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'wifi_icon_style',
        title: 'Wi-Fi icon style',
        subtitle: 'Select icon style for Wi-Fi status indicator',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'rounded',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Rounded', value: 'rounded'),
          StatusBarOption(label: 'Classic', value: 'classic'),
          StatusBarOption(label: 'Thin', value: 'thin'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'vowifi_icon_style',
        title: 'VoWiFi icon style',
        subtitle: 'Set icon family for VoWiFi indicator',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'balanced',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Balanced', value: 'balanced'),
          StatusBarOption(label: 'Compact', value: 'compact'),
          StatusBarOption(label: 'Hidden badge', value: 'badge_hidden'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'volte_icon_style',
        title: 'VoLTE icon style',
        subtitle: 'Configure VoLTE badge style and weight',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupStyle,
        defaultValue: 'brand',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Brand', value: 'brand'),
          StatusBarOption(label: 'Outlined', value: 'outlined'),
          StatusBarOption(label: 'Text only', value: 'text_only'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'simview_zoom',
        title: 'Icons size • SIM badge',
        subtitle: 'Scale SIM indicator badge size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_type_zoom',
        title: 'Icons size • mobile type',
        subtitle: 'Scale LTE/5G text indicator size',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 20.0,
        min: 1,
        max: 70,
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_inout_zoom',
        title: 'Icons size • in/out arrows',
        subtitle: 'Scale traffic direction arrows',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 100.0,
        min: 50,
        max: 200,
      ),
      const StatusBarSettingItem(
        legacyKey: 'network_font',
        title: 'Network font',
        subtitle: 'Choose font used by SIM and mobile type text',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupFont,
        defaultValue: 'sf_pro',
        options: <StatusBarOption>[
          StatusBarOption(label: 'SF Pro', value: 'sf_pro'),
          StatusBarOption(label: 'Inter', value: 'inter'),
          StatusBarOption(label: 'Roboto', value: 'roboto'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'network_rotation',
        title: 'Icons rotation',
        subtitle: 'Rotate network icon stack for stylized layouts',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupRotation,
        defaultValue: 0.0,
        min: -15,
        max: 15,
      ),
      const StatusBarSettingItem(
        legacyKey: 'mobile_inout_division',
        title: 'Spacing and division',
        subtitle: 'Adjust spacing between network icon components',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
      ),
    ],
    'notification_icons': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_enable',
        title: 'Show notification icons',
        subtitle: 'Display notification symbols in status bar',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'reverse_notification_sorting_order',
        title: 'Reverse icon order',
        subtitle: 'Show newest notification icon first',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupBehavior,
        defaultValue: false,
      ),
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_zoom',
        title: 'Notification icon size',
        subtitle: 'Scale visible notification icons',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 100.0,
        min: 10,
        max: 150,
      ),
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_division',
        title: 'Notification icon spacing',
        subtitle: 'Control distance between notification icons',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
      ),
      const StatusBarSettingItem(
        legacyKey: 'notif_icon_color',
        title: 'Notification icon color',
        subtitle: 'Apply tint to notification icon group',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FFFFFF',
      ),
    ],
    'status_icons': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_status_element_visible',
        title: 'Show status icons',
        subtitle: 'Display utility icons like Bluetooth and alarm',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_icon_zoom',
        title: 'Status icon size',
        subtitle: 'Scale utility icon size group-wide',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 100.0,
        min: 50,
        max: 200,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_icon_division',
        title: 'Status icon spacing',
        subtitle: 'Control spacing between utility icons',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_icon_color',
        title: 'Status icon color',
        subtitle: 'Choose tint used by status utility icons',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#FFFFFF',
      ),
    ],
    'date': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_date_element_visible',
        title: 'Show date',
        subtitle: 'Display date label in statusbar row',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: false,
      ),
      const StatusBarSettingItem(
        legacyKey: 'statusbar_date_format',
        title: 'Date format',
        subtitle: 'Pick date format pattern for the status area',
        controlType: StatusBarControlType.select,
        group: StatusBarStrings.groupTypography,
        defaultValue: 'EEE, dd MMM',
        options: <StatusBarOption>[
          StatusBarOption(label: 'Wed, 22 Apr', value: 'EEE, dd MMM'),
          StatusBarOption(label: '22/04/2026', value: 'dd/MM/yyyy'),
          StatusBarOption(label: 'April 22', value: 'MMMM d'),
        ],
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_date_zoom',
        title: 'Date text size',
        subtitle: 'Scale date text for better balance with clock',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 10.0,
        min: 1,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_date_division',
        title: 'Date spacing',
        subtitle: 'Adjust spacing around the date label',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 20.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_date_color',
        title: 'Date color',
        subtitle: 'Set date text color for contrast and depth',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#B7C6FF',
      ),
    ],
    'weather': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'elem_weather_element_visible',
        title: 'Show weather',
        subtitle: 'Display weather status in statusbar area',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'weather_anim_enable',
        title: 'Weather animation',
        subtitle: 'Enable subtle weather icon animation',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupAnimation,
        defaultValue: false,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_weather_zoom',
        title: 'Weather size',
        subtitle: 'Scale weather text and icon group',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupTypography,
        defaultValue: 16.0,
        min: 1,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_weather_division',
        title: 'Weather spacing',
        subtitle: 'Control weather group spacing from adjacent items',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 20.0,
        min: 0,
        max: 30,
      ),
      const StatusBarSettingItem(
        legacyKey: 'status_weather_color',
        title: 'Weather color',
        subtitle: 'Set weather icon and text tint',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#8DE8FF',
      ),
    ],
    'prompt_icon': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'statusbar_prompt_enable',
        title: 'Show prompt icon',
        subtitle: 'Enable prompt indicator in status row',
        controlType: StatusBarControlType.toggle,
        group: StatusBarStrings.groupVisibility,
        defaultValue: true,
      ),
      const StatusBarSettingItem(
        legacyKey: 'elem_prompt_scale',
        title: 'Prompt size',
        subtitle: 'Scale prompt icon size for subtle or strong presence',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupStyle,
        defaultValue: 75.0,
        min: 50,
        max: 150,
      ),
      const StatusBarSettingItem(
        legacyKey: 'elem_prompt_division',
        title: 'Prompt offset',
        subtitle: 'Move prompt icon horizontally for alignment',
        controlType: StatusBarControlType.slider,
        group: StatusBarStrings.groupSpacing,
        defaultValue: 0.0,
        min: -50,
        max: 50,
      ),
      const StatusBarSettingItem(
        legacyKey: 'statusbar_prompt_color',
        title: 'Prompt color',
        subtitle: 'Apply accent color to prompt icon',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupColor,
        defaultValue: '#E2B4FF',
      ),
    ],
    'background': <StatusBarSettingItem>[
      const StatusBarSettingItem(
        legacyKey: 'bg_clock',
        title: 'Clock background',
        subtitle: 'Customize background plate behind clock',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_battery',
        title: 'Battery background',
        subtitle: 'Set background style for battery element',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_sim1',
        title: 'SIM 1 background',
        subtitle: 'Set background for primary SIM indicator',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_sim2',
        title: 'SIM 2 background',
        subtitle: 'Set background for secondary SIM indicator',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_wifi',
        title: 'Wi-Fi background',
        subtitle: 'Customize background card behind Wi-Fi icon',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_speed',
        title: 'Network speed background',
        subtitle: 'Configure background for network speed text',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_notif',
        title: 'Notification icon background',
        subtitle: 'Set background for notification icon stack',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_status',
        title: 'Status icon background',
        subtitle: 'Set background plate for utility icons',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_weather',
        title: 'Weather background',
        subtitle: 'Customize weather element background layer',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_date',
        title: 'Date background',
        subtitle: 'Set background for date text element',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
      const StatusBarSettingItem(
        legacyKey: 'bg_prompt',
        title: 'Prompt icon background',
        subtitle: 'Set background for prompt icon plate',
        controlType: StatusBarControlType.color,
        group: StatusBarStrings.groupBackground,
        defaultValue: '#142D35',
      ),
    ],
  };
}
